import {initializeApp} from "https://www.gstatic.com/firebasejs/12.3.0/firebase-app.js";
import {getAuth,createUserWithEmailAndPassword,signInWithEmailAndPassword,signOut,onAuthStateChanged,setPersistence,browserLocalPersistence,updateProfile} from "https://www.gstatic.com/firebasejs/12.3.0/firebase-auth.js";
import {getFirestore,doc,getDoc,setDoc,collection,getDocs,query,orderBy,serverTimestamp} from "https://www.gstatic.com/firebasejs/12.3.0/firebase-firestore.js";
const firebaseConfig={apiKey:"AIzaSyBRjLmchJrdd5aVrWh5MUxOAYHpsAeKtRc",authDomain:"lowca-tablic.firebaseapp.com",projectId:"lowca-tablic",storageBucket:"lowca-tablic.firebasestorage.app",messagingSenderId:"822074746261",appId:"1:822074746261:web:16b290955e0f258a7a829c"};
const fb=initializeApp(firebaseConfig),auth=getAuth(fb),db=getFirestore(fb),DATA=window.PLATES,LS="lowca-tablic-backup-v2",$=x=>document.getElementById(x);let done=new Set(),mode="all",reg=false,user=null,timer;
await setPersistence(auth,browserLocalPersistence);
function authUI(){$('nickWrap').classList.toggle('hidden',!reg);$('authGo').textContent=reg?'Załóż konto':'Zaloguj się';$('switch').textContent=reg?'Masz konto? Zaloguj się':'Nie masz konta? Załóż konto';$('lead').textContent=reg?'Utwórz konto i wybierz nick do rankingu.':'Zaloguj się, aby zobaczyć kolekcję.';$('err').textContent=''}
$('switch').onclick=()=>{reg=!reg;authUI()};$('authGo').onclick=async()=>{let email=$('email').value.trim(),pass=$('pass').value,nick=$('nick').value.trim();$('err').textContent='';try{if(reg){if(nick.length<2)throw Error('Nick musi mieć co najmniej 2 znaki.');let c=await createUserWithEmailAndPassword(auth,email,pass);await updateProfile(c.user,{displayName:nick});await setDoc(doc(db,'users',c.user.uid),{nickname:nick,email,found:[],count:0,updatedAt:serverTimestamp()},{merge:true})}else await signInWithEmailAndPassword(auth,email,pass)}catch(e){$('err').textContent=(e.code||'').includes('invalid-credential')?'Nieprawidłowy e-mail lub hasło.':(e.code||'').includes('email-already')?'Konto już istnieje.':(e.code||'').includes('weak-password')?'Hasło musi mieć co najmniej 6 znaków.':e.message}};$('logout').onclick=()=>signOut(auth);
function local(){try{return new Set(JSON.parse(localStorage.getItem(LS)||'[]'))}catch{return new Set()}}function localSave(){localStorage.setItem(LS,JSON.stringify([...done]))}
async function load(){let ref=doc(db,'users',user.uid),s=await getDoc(ref),l=local();if(s.exists())done=new Set([...(s.data().found||[]),...l]);else done=l;localSave();await save(true)}
async function save(now=false){if(!user)return;clearTimeout(timer);$('saved').textContent='☁ zapisywanie…';timer=setTimeout(async()=>{try{await setDoc(doc(db,'users',user.uid),{nickname:user.displayName||user.email.split('@')[0],email:user.email,found:[...done],count:done.size,updatedAt:serverTimestamp()},{merge:true});$('saved').textContent='✓ zapisano w chmurze'}catch{$('saved').textContent='⚠ błąd synchronizacji'}},now?0:250)}
onAuthStateChanged(auth,async u=>{user=u;if(!u){$('auth').classList.remove('hidden');$('shell').classList.add('hidden');return}$('auth').classList.add('hidden');$('shell').classList.remove('hidden');$('who').textContent=u.displayName||u.email;await load();render()});
function stats(){let n=done.size,p=DATA.length,pc=100*n/p;$('count').textContent=n+' / '+p;$('pct').textContent=pc.toFixed(1).replace('.',',')+'%';$('fill').style.width=pc+'%'}
function render(){stats();let term=$('q').value.toLocaleLowerCase('pl'),w=$('woj').value,rows=DATA.filter(x=>(!term||(x.code+' '+x.place+' '+x.woj).toLocaleLowerCase('pl').includes(term))&&(!w||x.woj===w)&&(mode==='all'||mode==='done'&&done.has(x.code)||mode==='todo'&&!done.has(x.code))),g={};rows.forEach(x=>(g[x.woj]??=[]).push(x));$('app').innerHTML='';for(let [name,ps] of Object.entries(g)){let all=DATA.filter(x=>x.woj===name),got=all.filter(x=>done.has(x.code)).length,s=document.createElement('section');s.className='card';s.innerHTML=`<h2>${name}</h2><div class="sub">${got} / ${all.length} • ${Math.round(100*got/all.length)}%</div>`;ps.forEach(x=>{let r=document.createElement('label');r.className='row';r.innerHTML=`<span class="code">${x.code}</span><span>${x.place}</span><input type="checkbox" ${done.has(x.code)?'checked':''}>`;r.querySelector('input').onchange=e=>{e.target.checked?done.add(x.code):done.delete(x.code);localSave();save();render()};s.appendChild(r)});$('app').appendChild(s)}}
$('woj').innerHTML='<option value="">Wszystkie województwa</option>'+[...new Set(DATA.map(x=>x.woj))].sort().map(x=>`<option>${x}</option>`).join('');$('q').oninput=render;$('woj').onchange=render;function setMode(m,id){mode=m;['a','t','d'].forEach(x=>$(x).classList.remove('on'));$(id).classList.add('on');render()}$('a').onclick=()=>setMode('all','a');$('t').onclick=()=>setMode('todo','t');$('d').onclick=()=>setMode('done','d');
$('backup').onclick=()=>{let b=new Blob([JSON.stringify({version:3,date:new Date().toISOString(),done:[...done]},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='lowca-tablic-kopia.json';a.click()};$('restore').onclick=()=>$('file').click();$('file').onchange=async e=>{try{let o=JSON.parse(await e.target.files[0].text());done=new Set(o.done||[]);localSave();save();render();alert('Postęp przywrócony.')}catch{alert('Błędna kopia.')}};
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}async function ranking(){$('listView').classList.add('hidden');$('rankView').classList.remove('hidden');$('navList').classList.remove('on');$('navRank').classList.add('on');$('ranking').innerHTML='<div class="sub">Ładowanie…</div>';try{let s=await getDocs(query(collection(db,'users'),orderBy('count','desc'))),i=0,h='';s.forEach(d=>{let x=d.data();h+=`<div class="rankrow"><div class="pos">${++i}.</div><div><div class="nick">${esc(x.nickname||'Gracz')}</div><div class="muted">${d.id===user.uid?'To Ty':''}</div></div><div class="score">${x.count||0} / ${DATA.length}</div></div>`});$('ranking').innerHTML=h||'<div class="sub">Brak graczy.</div>'}catch(e){$('ranking').innerHTML='<div class="sub">Nie udało się pobrać rankingu.</div>'}}$('navRank').onclick=ranking;$('navList').onclick=()=>{$('rankView').classList.add('hidden');$('listView').classList.remove('hidden');$('navRank').classList.remove('on');$('navList').classList.add('on')};authUI();